### ISSUE TITLE
chmod should run in the background

### ISSUE THREAD

**Issue by daviddelikat** [joeybaker/docker-syncthing#10]
every time I start the container it runs chmod on the entire data set.  this takes a very long time and keeps the syncthing daemon from starting.

**Comment by joeybaker** [comment]
Hmmm… it's been while since I touched that code, but I think we need to do it to ensure the container has access to the contents of your data directory. 

That said, it might be reasonable to assume that we actually don't want to muck with permissions, or only do this on first run, or provide a flag. What do you think?

**Comment by daviddelikat** [comment]
I think simply running it in the background would be sufficient.  then it would not hold back the server from starting.

**Comment by joeybaker** [comment]
Makes sense. I'd happily take a PR!
